// === Catálogo ampliado de Obras Complementarias (extracto del PDF SAT 2025) ===
export const ListaobrasCatalogo = [
  { categoria: "Muros perimétricos o cercos", descripcion: "Muro de concreto armado que incluye armadura y cimentación, espesor hasta 0.25 m. Altura hasta 2.40 m.", unidad: "m2", valor: 446.51 },
  { categoria: "Muros perimétricos o cercos", descripcion: "Muro traslúcido de concreto armado (tipo UNI) y/o metálico que incluye cimentación. h: 2.40 m.", unidad: "m2", valor: 409.68 },
  { categoria: "Muros perimétricos o cercos", descripcion: "Muro de ladrillo tarrajeado con columnas de concreto armado. h: hasta 2.40 m.", unidad: "m2", valor: 324.16 },
  { categoria: "Muros perimétricos o cercos", descripcion: "Muro de ladrillo con columnas metálicas, h>2.40 m.", unidad: "m2", valor: 372.92 },
  { categoria: "Muros perimétricos o cercos", descripcion: "Muro de adobe o tapial tarrajeado.", unidad: "m2", valor: 145.23 },
  { categoria: "Portones y puertas", descripcion: "Puerta de fierro o aluminio h=2.20m, ancho ≤2.00m.", unidad: "m2", valor: 601.86 },
  { categoria: "Portones y puertas", descripcion: "Portón de fierro con plancha metálica h=3.00–4.00m.", unidad: "m2", valor: 418.66 },
  { categoria: "Tanques elevados", descripcion: "Tanque de concreto armado con capacidad hasta 5 m³.", unidad: "m3", valor: 1283.62 },
  { categoria: "Tanques elevados", descripcion: "Tanque elevado de plástico o fibra hasta 1.00 m³.", unidad: "m3", valor: 1043.22 },
  { categoria: "Cisternas, pozos sumideros, tanques sépticos", descripcion: "Cisterna de concreto armado con capacidad hasta 10 m³.", unidad: "m3", valor: 1203.93 },
  { categoria: "Cisternas, pozos sumideros, tanques sépticos", descripcion: "Pozo de ladrillo tarrajeado hasta 5 m³.", unidad: "m3", valor: 1136.83 },
  { categoria: "Piscinas, espejos de agua", descripcion: "Piscina de concreto armado con mayólica hasta 5 m³.", unidad: "m3", valor: 1436.21 },
  { categoria: "Piscinas, espejos de agua", descripcion: "Piscina de ladrillo con pintura.", unidad: "m3", valor: 984.44 },
  { categoria: "Losas deportivas y estacionamientos", descripcion: "Losa de concreto armado espesor 4''.", unidad: "m2", valor: 164.95 },
  { categoria: "Losas deportivas y estacionamientos", descripcion: "Asfalto espesor 2''.", unidad: "m2", valor: 136.96 },
  { categoria: "Rampas, gradas y escaleras de concreto", descripcion: "Escalera de concreto armado con acabados.", unidad: "m3", valor: 5988.09 },
  { categoria: "Rampas, gradas y escaleras de concreto", descripcion: "Rampa de concreto s/encofrado.", unidad: "m3", valor: 1689.40 },
  { categoria: "Postes de alumbrado", descripcion: "Poste de concreto/fierro con reflector instalado.", unidad: "und", valor: 2497.20 },
  { categoria: "Pasamanos metálicos", descripcion: "Pasamano metálico de tubo galvanizado de 2'' diam.", unidad: "ml", valor: 217.18 },
  { categoria: "Cercos metálicos", descripcion: "Cerco metálico con tubo 2'' y malla 2x2 Alam #8.", unidad: "m2", valor: 233.73 },
  { categoria: "Sardineles", descripcion: "Sardinel de concreto e=0.15m, h=0.35m con pintura.", unidad: "ml", valor: 137.20 },
  { categoria: "Pistas o pavimentos", descripcion: "Pista o losa de concreto de 6'' de espesor.", unidad: "m2", valor: 191.90 },
  { categoria: "Trampas de grasa", descripcion: "Trampa de concreto armado para grasa.", unidad: "m3", valor: 1319.54 },
];
